### ISSUE TITLE
What's this?

### ISSUE THREAD

**Issue by 625781186** [ChrisBrownie55/chatty#1]
npm start will show 
![image](https://user-images.githubusercontent.com/30521429/69884652-53894480-1314-11ea-8f2a-e184fa9d5649.png)

But I dont't know what this.

**Comment by andria-dev** [comment]
Looks like you didn't plug in any devices before trying to start up the project. If you would like to view the web version, then you should use `npm run web`. Note that I've actually abandoned this project for now due to a lack of suitable ways to use firebase in React Native, currently you have to use a special React Native version of firebase that doesn't have any hooks making development a pain.
